# Generated by Django 4.0.2 on 2022-03-08 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Created_at',
            new_name='created_at',
        ),
    ]
